import { useMemo, useState } from "react";
import AppShell from "../../components/AppShell";
import Icon from "../../components/Icon";
import { getNotices, createNotice, deleteNotice, toggleNoticeStatus } from "../../data/store";
import "./Phase2.css";

export default function PresidentNotices(){
  const [notices,setNotices]=useState(()=>getNotices()); const [query,setQuery]=useState(""); const [showForm,setShowForm]=useState(false);
  const [form,setForm]=useState({title:"",category:"Maintenance",body:"",audience:"All residents"});
  const filtered=useMemo(()=>notices.filter(n=>`${n.title} ${n.body} ${n.category}`.toLowerCase().includes(query.toLowerCase())),[notices,query]);
  const submit=e=>{e.preventDefault();if(!form.title.trim()||!form.body.trim())return;createNotice(form);setNotices(getNotices());setForm({title:"",category:"Maintenance",body:"",audience:"All residents"});setShowForm(false)};
  return <AppShell role="president" active="notices"><div className="page-head"><div><div className="eyebrow">Society communication</div><h1>Notices</h1><p>Create, publish, and manage announcements for residents.</p></div><button className="btn btn-primary" onClick={()=>setShowForm(v=>!v)}><Icon name="plus" size={15}/> Create notice</button></div>
    <div className="phase2-toolbar"><div className="filter-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notices..."/></div><div className="phase2-toolbar-stat"><span>Published</span><strong>{notices.filter(n=>n.status==="Published").length}</strong></div><div className="phase2-toolbar-stat"><span>Drafts</span><strong>{notices.filter(n=>n.status==="Draft").length}</strong></div></div>
    {showForm&&<form className="surface phase2-form" onSubmit={submit}><div className="section-header"><div><h2>Create a notice</h2><p>Keep residents informed with clear, timely announcements.</p></div></div><div className="phase2-form-grid"><label><span>Title</span><input className="input wide-input" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Water supply maintenance"/></label><label><span>Category</span><select className="select" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Maintenance</option><option>Security</option><option>Event</option><option>General</option></select></label><label className="wide"><span>Audience</span><select className="select" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option>All residents</option><option>Block A</option><option>Block B</option><option>Block C</option></select></label><label className="wide"><span>Message</span><textarea className="textarea" rows="5" value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Write the announcement..."/></label></div><div className="form-footer"><button type="button" className="btn btn-secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="btn btn-primary">Publish notice</button></div></form>}
    <div className="notice-grid">{filtered.map(n=><article className="surface notice-card" key={n.id}><div className="notice-card-top"><span className="notice-type"><Icon name="building" size={15}/>{n.category}</span><span className={`status ${n.status==="Published"?"status-resolved":"status-pending"}`}>{n.status}</span></div><h2>{n.title}</h2><p>{n.body}</p><div className="notice-meta"><span>{n.date} · {n.time}</span><span>{n.audience}</span></div><div className="notice-actions"><button className="text-link" onClick={()=>{toggleNoticeStatus(n.id);setNotices(getNotices())}}>{n.status==="Published"?"Unpublish":"Publish"}</button><button className="text-link danger-link" onClick={()=>{deleteNotice(n.id);setNotices(getNotices())}}>Delete</button></div></article>)}</div>
    {!filtered.length&&<div className="surface empty-state"><strong>No notices found</strong><p>Create your first society announcement.</p></div>}
  </AppShell>
}
