import { useMemo, useState } from "react";
import AppShell from "../../components/AppShell";
import Icon from "../../components/Icon";
import { getResidents, createResident, toggleResidentStatus } from "../../data/store";
import "./Phase2.css";

export default function PresidentResidents(){
  const [residents,setResidents]=useState(()=>getResidents()); const [query,setQuery]=useState(""); const [block,setBlock]=useState("All Blocks"); const [showForm,setShowForm]=useState(false);
  const [form,setForm]=useState({name:"",flat:"",block:"A",phone:"",email:""});
  const filtered=useMemo(()=>residents.filter(r=>(block==="All Blocks"||r.block===block)&&`${r.name} ${r.flat} ${r.phone} ${r.email}`.toLowerCase().includes(query.toLowerCase())),[residents,block,query]);
  const submit=e=>{e.preventDefault();if(!form.name||!form.flat)return;createResident(form);setResidents(getResidents());setForm({name:"",flat:"",block:"A",phone:"",email:""});setShowForm(false)};
  return <AppShell role="president" active="residents"><div className="page-head"><div><div className="eyebrow">Community directory</div><h1>Residents</h1><p>Manage residents, flat details, contact information, and account status.</p></div><button className="btn btn-primary" onClick={()=>setShowForm(v=>!v)}><Icon name="plus" size={15}/> Add resident</button></div>
    <div className="phase2-toolbar"><div className="filter-search"><Icon name="search" size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search residents or flats..."/></div><select className="select compact-select" value={block} onChange={e=>setBlock(e.target.value)}><option>All Blocks</option><option>A</option><option>B</option><option>C</option></select><div className="phase2-toolbar-stat"><span>Residents</span><strong>{residents.length}</strong></div></div>
    {showForm&&<form className="surface phase2-form" onSubmit={submit}><div className="section-header"><div><h2>Add resident</h2><p>Create a resident profile for the society directory.</p></div></div><div className="phase2-form-grid"><label><span>Full name</span><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Resident name"/></label><label><span>Flat</span><input className="input" value={form.flat} onChange={e=>setForm({...form,flat:e.target.value})} placeholder="204"/></label><label><span>Block</span><select className="select" value={form.block} onChange={e=>setForm({...form,block:e.target.value})}><option>A</option><option>B</option><option>C</option></select></label><label><span>Phone</span><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone number"/></label><label className="wide"><span>Email</span><input className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="resident@example.com"/></label></div><div className="form-footer"><button type="button" className="btn btn-secondary" onClick={()=>setShowForm(false)}>Cancel</button><button className="btn btn-primary">Add resident</button></div></form>}
    <div className="surface table-surface"><div className="table-head resident-table-head"><span>Resident</span><span>Flat</span><span>Contact</span><span>Status</span><span>Joined</span><span>Action</span></div>{filtered.map(r=><div className="table-row resident-table-row" key={r.id}><div><div className="table-title">{r.name}</div><div className="table-sub">{r.id}</div></div><div>{r.flat}</div><div><div>{r.phone}</div><div className="table-sub">{r.email}</div></div><div><span className={`status ${r.status==="Active"?"status-resolved":"status-pending"}`}>{r.status}</span></div><div>{r.joined}</div><div className="table-action"><button className="btn btn-secondary compact-action" onClick={()=>{toggleResidentStatus(r.id);setResidents(getResidents())}}>{r.status==="Active"?"Deactivate":"Activate"}</button></div></div>)}<div className="table-pagination"><span>Showing {filtered.length} of {residents.length}</span></div></div>
  </AppShell>
}
