import {useMemo} from "react"; import {useNavigate,useParams} from "react-router-dom"; import AppShell from "../../components/AppShell"; import Icon from "../../components/Icon"; import {getComplaint} from "../../data/store";
export default function ComplaintDetails(){const navigate=useNavigate(),{id}=useParams(),complaint=useMemo(()=>getComplaint(id),[id]); if(!complaint)return <AppShell role="resident" active="complaints"><div className="empty-state surface"><strong>Complaint not found</strong><p>This complaint may have been removed from the local demo data.</p><button className="btn btn-primary" style={{marginTop:16}} onClick={()=>navigate("/resident/complaints")}>Back to complaints</button></div></AppShell>;
 const statusClass=complaint.status==="Resolved"?"status-resolved":complaint.status==="In Progress"?"status-progress":"status-review",isResolved=complaint.status==="Resolved";
 return <AppShell role="resident" active="complaints"><button className="back-link" onClick={()=>navigate("/resident/complaints")}><Icon name="back" size={15}/> Back to my complaints</button><div className="details-layout"><div className="details-main"><div className="surface surface-pad"><div className="details-title-row"><div><h1>{complaint.title}</h1><div className="details-id">{complaint.id} · Block {complaint.block}, Flat {complaint.flat}</div></div><span className={`status ${statusClass}`}>{complaint.status}</span></div></div>
 <section className="surface surface-pad"><div className="details-section-header"><div><h2 className="details-card-title">Complaint timeline</h2><p className="section-note">A clear view of what happens next.</p></div><span className="timeline-badge">{complaint.timeline.length} updates</span></div><div className="timeline">{complaint.timeline.map((item,index)=><div className={`timeline-item ${index<complaint.timeline.length-1?"completed":"current"}`} key={`${item.label}-${item.time}`}><div className="timeline-dot"/><div className="timeline-copy"><h3>{item.label}</h3><p>{item.time}</p><span>{item.note}</span></div></div>)}{!isResolved&&<div className="timeline-item"><div className="timeline-dot"/><div className="timeline-copy"><h3>Resolved</h3><p>Awaiting completion</p><span>The complaint will be marked resolved after the work is completed.</span></div></div>}</div></section>
 <section className="surface surface-pad"><h2 className="details-card-title">Description</h2><p className="body-copy">{complaint.description}</p></section>
 {complaint.attachments?.length>0&&<section className="surface surface-pad"><div className="details-section-header"><div><h2 className="details-card-title">Attachments</h2><p className="section-note">Evidence included with your report.</p></div><span className="timeline-badge">{complaint.attachments.length} files</span></div><div className="details-attachments">{complaint.attachments.map(file=><div className="detail-attachment" key={file}><span className="attachment-file-icon"><Icon name="paperclip" size={14}/></span><div><strong>{file}</strong><span>Attached to complaint</span></div></div>)}</div></section>}
 <section className="surface surface-pad"><h2 className="details-card-title">Society response</h2><div className="response" style={{marginTop:14}}><div className="avatar">P</div><div><strong>Society President</strong><span>Latest management update</span><p>{complaint.response}</p></div></div></section>
 {isResolved&&<section className="feedback-prompt surface"><div><span className="eyebrow">Issue resolved</span><h2>How did this resolution feel?</h2><p>Leave a quick rating so your society can improve.</p></div><button className="btn btn-primary" onClick={()=>navigate(`/resident/feedback?complaint=${complaint.id}`)}>Share feedback <Icon name="arrow" size={15}/></button></section>}
 </div><aside className="details-side"><section className="surface surface-pad"><h2 className="details-card-title">About this issue</h2><div className="kv-list" style={{marginTop:17}}><div className="kv-row"><span>Category</span><strong>{complaint.category}</strong></div><div className="kv-row"><span>Priority</span><strong className={`priority-${complaint.priority.toLowerCase()}`}>{complaint.priority}</strong></div><div className="kv-row"><span>Location</span><strong>Block {complaint.block} · Flat {complaint.flat}</strong></div><div className="kv-row"><span>Submitted</span><strong>{complaint.date}</strong></div></div></section><section className="surface surface-pad"><h2 className="details-card-title">Need another report?</h2><p className="body-copy">Raise a separate complaint for another issue in your home or society.</p><button className="btn btn-primary" style={{marginTop:15,width:"100%"}} onClick={()=>navigate("/resident/complaints/new")}>Report another issue</button></section></aside></div></AppShell>}
