import { useMemo, useState } from "react";
import { useSearchParams,useNavigate } from "react-router-dom";
import AppShell from "../../components/AppShell"; import Icon from "../../components/Icon"; import { getComplaints } from "../../data/store";
export default function MyComplaints(){
 const navigate=useNavigate(),[params]=useSearchParams(),[search,setSearch]=useState(params.get("search")||""),[status,setStatus]=useState("All Status"),[category,setCategory]=useState("All Categories");
 const complaints=getComplaints(),categories=[...new Set(complaints.map(c=>c.category))],filtered=useMemo(()=>complaints.filter(c=>{const ms=!search.trim()||`${c.id} ${c.title} ${c.category} ${c.description}`.toLowerCase().includes(search.toLowerCase());return ms&&(status==="All Status"||c.status===status)&&(category==="All Categories"||c.category===category)}),[complaints,search,status,category]);
 const statusClass=v=>v==="Resolved"?"status-resolved":v==="In Progress"?"status-progress":"status-review"; const total=complaints.length,inProgress=complaints.filter(c=>c.status==="In Progress").length,resolved=complaints.filter(c=>c.status==="Resolved").length;
 return <AppShell role="resident" active="complaints"><div className="page-head complaint-page-head"><div><button className="back-link" onClick={()=>navigate("/resident/dashboard")}><Icon name="back" size={15}/> Back to dashboard</button><div className="eyebrow">My activity</div><h1>My complaints</h1><p>View and track every request you've raised with society management.</p></div><button className="btn btn-primary" onClick={()=>navigate("/resident/complaints/new")}><Icon name="plus" size={15}/> New complaint</button></div>
  <div className="summary-inline"><div className="summary-mini"><span>Total complaints</span><strong>{String(total).padStart(2,"0")}</strong></div><div className="summary-mini"><span>In progress</span><strong>{String(inProgress).padStart(2,"0")}</strong></div><div className="summary-mini"><span>Resolved</span><strong>{String(resolved).padStart(2,"0")}</strong></div></div>
  <section className="section-block"><div className="section-header"><div><h2>Complaint history</h2><p>{filtered.length} shown</p></div></div><div className="complaint-filters"><label className="filter-search"><Icon name="search" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by complaint, category or ID..."/></label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option>All Status</option><option>Under Review</option><option>In Progress</option><option>Resolved</option></select><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option>All Categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="list-surface">{filtered.map(c=><div className="list-row" key={c.id} onClick={()=>navigate(`/resident/complaints/${c.id}`)}><div className="list-main"><div className="list-title">{c.title}</div><div className="list-meta">{c.id} · {c.category} · {c.date}</div></div><div className="row-actions"><span className={`status ${statusClass(c.status)}`}>{c.status}</span><Icon name="chevron" size={17} className="row-chevron"/></div></div>)}{filtered.length===0&&<div className="empty-state"><strong>No complaints match your filters</strong><p>Try a different search term, status or category.</p></div>}</div></section>
 </AppShell>
}
