import { useMemo,useRef,useState } from "react"; import {useNavigate} from "react-router-dom"; import AppShell from "../../components/AppShell"; import Icon from "../../components/Icon"; import {createComplaint} from "../../data/store";
export default function SubmitComplaint(){
 const navigate=useNavigate(),inputRef=useRef(null),[priority,setPriority]=useState("Medium"),[title,setTitle]=useState(""),[category,setCategory]=useState("Maintenance"),[block,setBlock]=useState("B"),[flat,setFlat]=useState("204"),[description,setDescription]=useState(""),[files,setFiles]=useState([]),[submitting,setSubmitting]=useState(false);
 const fileSummary=useMemo(()=>files.map(f=>`${f.name} · ${(f.size/1024).toFixed(0)} KB`),[files]); const handleFiles=e=>{const next=Array.from(e.target.files||[]).slice(0,5);setFiles(cur=>[...cur.filter(old=>!next.some(n=>n.name===old.name)),...next].slice(0,5))}; const removeFile=name=>setFiles(cur=>cur.filter(f=>f.name!==name));
 const submit=e=>{e.preventDefault();if(!title.trim()||!description.trim())return;setSubmitting(true);const complaint=createComplaint({title:title.trim(),category,block,flat,priority,description:description.trim(),attachments:files.map(f=>f.name)});navigate(`/resident/complaints/${complaint.id}`)};
 return <AppShell role="resident" active="complaints" section="section-form"><button className="back-link" onClick={()=>navigate("/resident/complaints")}><Icon name="back" size={15}/> Back to complaints</button><div className="page-head"><div><div className="eyebrow">Resident service</div><h1>Report an issue</h1><p>Tell us what's wrong and we'll route it to the right society team.</p></div></div><form onSubmit={submit} className="form-layout"><div className="form-steps"><div className="form-step active"><span className="step-num">01</span><strong>Issue details</strong></div><div className="form-step active"><span className="step-num">02</span><strong>Priority</strong></div><div className="form-step active"><span className="step-num">03</span><strong>Description</strong></div><div className="form-step active"><span className="step-num">04</span><strong>Evidence</strong></div></div><div>
 <section className="surface form-card"><h2>01 · Issue details</h2><p className="form-help">Give the management team enough context to identify the request.</p><div className="field"><label>What is the issue?</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Water leakage in Block B" required/></div><div className="field-grid three"><div className="field"><label>Category</label><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option>Maintenance</option><option>Electricity</option><option>Security</option><option>Cleanliness</option><option>Parking</option></select></div><div className="field"><label>Block</label><select className="select" value={block} onChange={e=>setBlock(e.target.value)}><option>B</option><option>A</option><option>C</option></select></div><div className="field"><label>Flat</label><select className="select" value={flat} onChange={e=>setFlat(e.target.value)}><option>204</option><option>102</option><option>305</option></select></div></div></section>
 <section className="surface form-card"><h2>02 · Priority</h2><p className="form-help">Choose how quickly you think the issue needs attention.</p><div className="field"><div className="choice-grid">{[["Low","Can wait"],["Medium","Needs attention"],["High","Requires urgent action"]].map(([v,d])=><label className={`choice ${priority===v?"selected":""}`} key={v}><input type="radio" name="priority" value={v} checked={priority===v} onChange={e=>setPriority(e.target.value)}/><strong>{v}</strong><span>{d}</span></label>)}</div></div></section>
 <section className="surface form-card"><h2>03 · Description</h2><p className="form-help">Add details that can help the team understand what happened and where.</p><div className="field"><label>Description</label><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell us what happened..." required/></div></section>
 <section className="surface form-card"><h2>04 · Add photos or documents</h2><p className="form-help">Add up to 5 images or PDF files to help the team understand the issue.</p><div className="upload-zone" onClick={()=>inputRef.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")inputRef.current?.click()}}><span className="upload-icon"><Icon name="plus" size={17}/></span><strong>Upload evidence</strong><span>JPG, PNG or PDF · max 5 files</span><input ref={inputRef} type="file" accept="image/*,.pdf" multiple hidden onChange={handleFiles}/></div>{files.length>0&&<div className="attachment-list">{fileSummary.map((label,i)=>{const file=files[i];return <div className="attachment-chip" key={`${file.name}-${i}`}><Icon name="paperclip" size={14}/><span>{label}</span><button type="button" aria-label={`Remove ${file.name}`} onClick={e=>{e.stopPropagation();removeFile(file.name)}}>×</button></div>})}</div>}<div className="form-footer"><button type="button" className="btn btn-secondary" onClick={()=>navigate("/resident/complaints")}>Cancel</button><button className="btn btn-primary" type="submit" disabled={submitting}>{submitting?"Submitting...":"Submit report"} <Icon name="arrow" size={15}/></button></div></section>
 </div></form></AppShell>
}
